name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cfg:
        # - conda-env: test_env
        #   python-version: 3.6
        - conda-env: test_env
          python-version: 3.7
        # - conda-env: test_env
        #   python-version: 3.8

    env: 
      PYVER: ${{ matrix.cfg.python-version }}
      CONDA_ENV: ${{ matrix.cfg.conda-env }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup Information
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
        conda --version
    - name: Create Environment
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate
        python devtools/scripts/create_conda_env.py -n=test -p=$PYVER devtools/conda-envs/$CONDA_ENV.yaml
    - name: Install
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        python -m pip install . --no-deps
    - name: Libxc Python Library
      shell: bash
      run: |
        cd ~
        wget --content-disposition  http://www.tddft.org/programs/libxc/down.php?file=5.0.0/libxc-5.0.0.tar.gz
        tar xf libxc-5.0.0.tar.gz
        cd libxc-5.0.0/
        python -m pip install . --no-deps
    - name: Environment Information
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        conda list --show-channel-urls
    - name: PyTest
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        python -c "import pylibxc"
        pytest -rws -v --cov=CADMium --color=yes --cov-report=xml CADMium/
    - name: CodeCov  
      uses: codecov/codecov-action@v1
